import type { Config } from "tailwindcss";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "5%",
      screens: {
        containerFull: "100%",
        containerLarge: "1440px",
      },
    },
    extend: {
      colors: {
        red25: "#FCEBEC",
        red50: "#F9D6D7",
        red100: "#F2B1B5",
        red200: "#E98A91",
        red300: "#DF646C",
        red400: "#D43E48",
        red500: "#8A1724",
        red600: "#73131D",
        red700: "#5D0F17",
        red800: "#460B11",
        red900: "#30070B",
        red950: "#1E0407",
        gray25: "#F6F6F6",
        gray50: "#F6F6F6",
        gray100: "#E7E7E7",
        gray200: "#D1D1D1",
        gray300: "#B0B0B0",
        gray400: "#888888",
        gray500: "#6D6D6D",
        gray600: "#5D5D5D",
        gray700: "#4F4F4F",
        gray800: "#454545",
        gray900: "#3D3D3D",
        gray950: "#191919",
        grayScale: "#494949",
        grayCoverage: "#FBFBFB",
        blueScale: "#02232D",
        bgSilderControl: "#A7A7A7",
        white: "#FFFFFF",
        light: "#FCEBEC",
        redSTD: "#8A1724",
        dark: "#5D0F17",
        auxiliary: "#F44336",
        green10: "#EEFFF3",
        green25: "#EAFBEC",
        green50: "#D3F6D9",
        green75: "#B1E4BF",
        green100: "#ADF0B8",
        green200: "#87E997",
        green300: "#61E277",
        green400: "#3DDB5B",
        green500: "#1EB03E",
        green600: "#189032",
        green700: "#137026",
        green800: "#0E501B",
        green900: "#093012",
        green950: "#051F0C",
        greenCoverage: "#00A650",
        blueBTN: "#239DE4",
        blueBORDER: "#185195",
      },
      backgroundImage: {
        BgHomeHelPlans: "url(/assets/img/bg-HomeHelpPlans.webp)",
        BgContact: "url(/assets/img/bg-contact.webp)",
        BgContactMobile: "url(/assets/img/bg-contactMobile.webp)",
        BgContactTablet: "url(/assets/img/bg-contactTablet.webp)",
      },
      fontFamily: {
        openSans: ["Open Sans", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        lato: ["Lato", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "bounce-x": "bounce-x 1s infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "modal-enter-mobile": "modal-enter-mobile 0.3s ease-out",
        "modal-exit-mobile": "modal-exit-mobile 0.3s ease-in",
      },
    },
    screens: {
      "@mobile": "639px",
      "@tablet": "999px",
      "@laptop": "1025px",
      "@Desktop": "1281px",
      "@Desktop1440": "1440px",
      "@LargeDesktop": "1537px",
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    function ({ addUtilities, theme }: any) {
      const newUtilities = {
        ".TypLato32w600": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "32px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypLato18w600": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypLato14w600": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypLato14w400": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },

        ".btnYes": {
          color: theme("colors.greenCoverage"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "4px",
          borderRadius: "8px",
          background: theme("colors.green10"),
          border: "1px solid #B1E4BF",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },

        ".btnNot": {
          color: theme("colors.gray300"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "500",
          lineHeight: "140%",
          letterSpacing: "-0.28px",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "4px",
          borderRadius: "8px",
          background: theme("colors.gray50"),
          border: "1px solid #E7E7E7",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".btnPrimary": {
          height: "40px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "6px",
          background: theme("colors.redSTD"),
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnPrimaryMD": {
          height: "36px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "6px",
          background: theme("colors.redSTD"),
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnPrimarySM": {
          height: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "6px",
          background: theme("colors.redSTD"),
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.white"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnPrimaryADD": {
          height: "40px",
          width: "40px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borderRadius: "6px",
          /* background: theme("colors.redSTD"), */
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
        },
        ".btnPrimaryADDmd": {
          height: "36px",
          width: "36px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borderRadius: "6px",
          /* background: theme("colors.redSTD"), */
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
        },
        ".btnPrimaryADDsm": {
          height: "32px",
          width: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borderRadius: "6px",
          /* background: theme("colors.redSTD"), */
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
        },
        ".btnAddOFF": {
          height: "40px",
          width: "40px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borders: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
        },
        ".btnAddOFFmd": {
          height: "36px",
          width: "36px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borders: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
        },
        ".btnAddOFFsm": {
          height: "32px",
          width: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borders: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
        },
        ".btnAddDefault": {
          height: "40px",
          width: "40px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
        ".btnAddDefaultMD": {
          height: "36px",
          width: "36px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
        ".btnAddDefaultSM": {
          height: "32px",
          width: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
        ".btnAddDefaultOFF": {
          height: "40px",
          width: "40px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
        ".btnAddDefaultOFFmd": {
          height: "36px",
          width: "36px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
        ".btnAddDefaultOFFsm": {
          height: "32px",
          width: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        },
        ".btnPrimaryOFF": {
          height: "40px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "6px",
          background: theme("colors.gray200"),
          boxShadow:
            " 0 1px 2px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.gray400"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnPrimaryOFFmd": {
          height: "36px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "6px",
          background: theme("colors.gray200"),
          boxShadow:
            " 0 1px 2px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.gray400"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnPrimaryOFFsm": {
          height: "32px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "6px",
          background: theme("colors.gray200"),
          boxShadow:
            " 0 1px 2px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.gray400"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".pBTN": {
          padding: "12px 16px ",
        },
        ".pBTNAddLeft": {
          padding: "7px 16px 7px 12px",
        },
        ".pBTNAddRight": {
          padding: "7px 12px 7px 16px",
        },

        ".btnSecondary": {
          height: "40px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          border: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.grayScale"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnSecondaryMD": {
          height: "36px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          border: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.grayScale"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnSecondarySM": {
          height: "32px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          border: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
          boxShadow:
            " 0 1px 4px 0 rgba(0, 0, 0, 0.08), 0 1px 2px 0 rgba(25, 25, 25, 0.08)",
          color: theme("colors.grayScale"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnSecondaryOFF": {
          height: "40px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          border: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
          color: theme("colors.gray200"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnSecondaryOFFmd": {
          height: "36px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          border: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
          color: theme("colors.gray200"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnSecondaryOFFsm": {
          height: "32px",
          display: "inline-flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          border: "1px solid #EBEBEB",
          borderRadius: "6px",
          background: theme("colors.white"),
          color: theme("colors.gray200"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnTertiary": {
          display: "inline-flex",
          padding: "2px 0px",
          justifyContent: "center",
          alignItems: "center",
          gap: "10px",
          color: theme("colors.grayScale"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnTertiaryOFF": {
          display: "inline-flex",
          padding: "2px 0px",
          justifyContent: "center",
          alignItems: "center",
          gap: "10px",
          color: theme("colors.gray200"),
          fontFamily: "var(--font-inter) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "130%",
        },
        ".btnLink": {
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },

        ".btnLinkForm": {
          display: "inline-flex",
          padding: "12px 24px",
          justifyContent: "center",
          alignItems: "center",
          gap: "8px",
          borderRadius: "4px",
          border: "1px solid #8A1724",
          /* background: theme("colors.white"),
          boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.08)", */
          color: theme("colors.redSTD"),
        },
        ".textbtnLink": {
          color: theme("colors.redSTD"),
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".textBtn": {
          fontFamily: "var(--font-inter) ",
          fontSize: "16px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "150%",
        },
        ".bgOverlayMobile": {
          background: "rgba(58, 58, 58, 0.58)",
          "backdrop-filter": "blur(5px)", // Use kebab-case
          "-webkit-backdrop-filter": "blur(5px)", // Adicione prefixo para compatibilidade com navegadores WebKit
        },
        ".scrollbar-hidden": {
          "-ms-overflow-style": "none" /* IE e Edge */,
          "scrollbar-width": "none" /* Firefox */,
        },
        ".scrollbar-hide::-webkit-scrollbar": {
          display: "none" /* Chrome, Safari e Opera */,
        },
        safelist: [
          "snap-x",
          "snap-mandatory",
          "snap-center",
          "bg-BgCardModalComparePlans",
          "bg-BgCardModalComparePlansMobile",
          "BGStepB0",
          "BGCardStepB0",
        ],
      };
      addUtilities(newUtilities);
    },
  ],
} satisfies Config;
