import type { Config } from "tailwindcss";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "5%",
      screens: {
        containerFull: "100%",
        containerLarge: "1440px",
      },
    },
    extend: {
      colors: {
        red25: "#FCEBEC",
        red50: "#F9D6D7",
        red100: "#F2B1B5",
        red200: "#E98A91",
        red300: "#DF646C",
        red400: "#D43E48",
        red500: "#8A1724",
        red600: "#73131D",
        red700: "#5D0F17",
        red800: "#460B11",
        red900: "#30070B",
        red950: "#1E0407",
        gray25: "#FBFBFB",
        gray50: "#F6F6F6",
        gray100: "#E7E7E7",
        gray200: "#D1D1D1",
        gray300: "#B0B0B0",
        gray400: "#888888",
        gray500: "#6D6D6D",
        gray600: "#5D5D5D",
        gray700: "#4F4F4F",
        gray800: "#454545",
        gray900: "#3D3D3D",
        green25: "#EAFBEC",
        green50: "#D3F6D9",
        green100: "#ADF0B8",
        green200: "#87E997",
        green300: "#61E277",
        green400: "#3DDB5B",
        green500: "#1EB03E",
        green600: "#189032",
        green700: "#137026",
        green800: "#0E501B",
        green900: "#093012",
        green950: "#051F0C",
        SucessBG: "#D1E7DD",
        SucessBorder: "#A3CFBB",
        SucessDark: "#0A3622",
        SucessDefault: "#00A650",
        InfoBG: "#CFF4FC",
        InfoBorder: "#9EEAF9",
        InfoDark: "#055160",
        InfoDefault: "#1759D3",
        WarningBG: "#FFFBED",
        WarningBorder: "#FCD28C",
        WarningDark: "#664D03",
        WarningDefault: "#E69A1A",
        DangerBG: "#FFF6F8",
        DangerBorder: "#FFA7A0",
        DangerDark: "#58151C",
        DangerDefault: "#DF554B",
      },
      backgroundImage: {
        BgHomeHelPlans: "url(/assets/img/bg-HomeHelpPlans.webp)",
        BgContact: "url(/assets/img/bg-contact.webp)",
        BgContactMobile: "url(/assets/img/bg-contactMobile.webp)",
        BgContactTablet: "url(/assets/img/bg-contactTablet.webp)",
      },
      fontFamily: {
        openSans: ["Open Sans", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        lato: ["Lato", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "bounce-x": "bounce-x 1s infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "modal-enter-mobile": "modal-enter-mobile 0.3s ease-out",
        "modal-exit-mobile": "modal-exit-mobile 0.3s ease-in",
      },
    },
    screens: {
      "@mobile": "639px",
      "@tablet": "999px",
      "@laptop": "1025px",
      "@Desktop": "1281px",
      "@Desktop1440": "1440px",
      "@LargeDesktop": "1537px",
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    function ({ addUtilities, theme }: any) {
      const newUtilities = {
        ".TypLato32w600": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "32px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypLato18w600": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "18px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypLato14w600": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypLato14w400": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-lato) ",
          fontSize: "14px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "140%",
          letterSpacing: "-0.36px",
        },
        ".TypInter12w400": {
          color: theme("colors.gray700"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
        },
        ".TypInter12w400off": {
          color: theme("colors.gray300"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
        },

        ".BadgeDefault": {
          color: theme("colors.gray800"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.gray25"),
          border: "1px solid #EBEBEB",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeDefaultOFF": {
          color: theme("colors.gray300"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.gray100"),
          border: "1px solid #EBEBEB",
        },
        ".BadgeStatus": {
          height: "24px",
          color: theme("colors.gray800"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px 2px 4px",
          alignItems: "center",
          gap: "2px",
          borderRadius: "8px",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeSucesssFill": {
          height: "24px",
          color: theme("colors.SucessDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px 2px 4px",
          alignItems: "center",
          gap: "2px",
          borderRadius: "8px",
          background: theme("colors.green25"),
          border: "1px solid #A3CFBB",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeInfoFill": {
          height: "24px",
          color: theme("colors.InfoDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px 2px 4px",
          alignItems: "center",
          gap: "2px",
          borderRadius: "8px",
          background: theme("colors.InfoBG"),
          border: "1px solid #A7C5FD",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeWarningFill": {
          height: "24px",
          color: theme("colors.WarningDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px 2px 4px",
          alignItems: "center",
          gap: "2px",
          borderRadius: "8px",
          background: theme("colors.WarningBG"),
          border: "1px solid #FCD28C",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeDangerFill": {
          height: "24px",
          color: theme("colors.DangerDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px 2px 4px",
          alignItems: "center",
          gap: "2px",
          borderRadius: "8px",
          background: theme("colors.DangerBG"),
          border: "1px solid #FFA7A0",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },

        ".BadgeStatusArrow": {
          height: "24px",
          color: theme("colors.gray800"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.white"),
          border: "1px solid #EBEBEB",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeArrowSucessFill": {
          height: "24px",
          color: theme("colors.SucessDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.green25"),
          border: "1px solid #A3CFBB",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeArrowINFOFill": {
          height: "24px",
          color: theme("colors.InfoDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.InfoBG"),
          border: "1px solid #A7C5FD",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeArrowWarningFill": {
          height: "24px",
          color: theme("colors.WarningDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.WarningBG"),
          border: "1px solid #FCD28C",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".BadgeArrowDangerFill": {
          height: "24px",
          color: theme("colors.DangerDefault"),
          fontFamily: "var(--font-inter) ",
          fontSize: "12px",
          fontStyle: "normal",
          fontWeight: "400",
          lineHeight: "150%",
          display: "flex",
          padding: "2px 8px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "8px",
          background: theme("colors.DangerBG"),
          border: "1px solid #FFA7A0",
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".OnlyDoubleArrow": {
          height: "24px",
          width: "24px",
          display: "flex",
          justifyContent: "center",
          padding: "2px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "999px",
          border: "1px solid #EBEBEB",
          background: theme("colors.gray25"),
          boxShadow:
            "0px 1px 4px 0px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(25, 25, 25, 0.08)",
        },
        ".OnlyDoubleArrowOFF": {
          height: "24px",
          width: "24px",
          display: "flex",
          justifyContent: "center",
          padding: "2px",
          alignItems: "center",
          gap: "10px",
          borderRadius: "999px",
          border: "1px solid #EBEBEB",
          background: theme("colors.gray100"),
        },

        ".bgOverlayMobile": {
          background: "rgba(58, 58, 58, 0.58)",
          "backdrop-filter": "blur(5px)", // Use kebab-case
          "-webkit-backdrop-filter": "blur(5px)", // Adicione prefixo para compatibilidade com navegadores WebKit
        },
        ".scrollbar-hidden": {
          "-ms-overflow-style": "none" /* IE e Edge */,
          "scrollbar-width": "none" /* Firefox */,
        },
        ".scrollbar-hide::-webkit-scrollbar": {
          display: "none" /* Chrome, Safari e Opera */,
        },
        safelist: [
          "snap-x",
          "snap-mandatory",
          "snap-center",
          "bg-BgCardModalComparePlans",
          "bg-BgCardModalComparePlansMobile",
          "BGStepB0",
          "BGCardStepB0",
        ],
      };
      addUtilities(newUtilities);
    },
  ],
} satisfies Config;
